### ISSUE TITLE
 downloader.py error

### ISSUE THREAD

**Issue by theandychung** [icelam/anime1-downloader#15] opened 2022-09-10 01:15 UTC
## Environment and package version
Python 3.9.9 with english windows 10

## Reproduction link / code sample
NA

## Steps to reproduce
execute `pipenv run python anime1download`

## What is expected?
Prompt of the downloader asking which anime to download.

## What is actually happening?
```
  File "anime1download\__main__.py", line 3, in <module>
    from cli import downloader
  File "<fstring>", line 1
    (error=)
```

**Comment by icelam** [comment] 2022-09-13 09:14
Hi @theandychung, I tried to setup a Windows 10 environment inside Virtual Box but I couldn't reproduce the issue. Python 3.9.9 was setup on the English OS and it works fine.

![Capture](https://user-images.githubusercontent.com/6780420/189860569-cb4d6634-b21f-4c80-8e4f-fd3343a91d9e.PNG)

I will need more information to debug the issue. The stacktrace you provided in the "What is actually happening?" section seems doesn't provide any name of the error happening. Is that the complete stacktrace already? It would be helpful if you can provide some screen recording or screenshots of how this error can be reproduced.

Or if you found the cause of the problem, pull request is also welcomed.

**Comment by icelam** [comment] 2023-01-01 08:36
I will close this issue for now, as I haven't received any updates in several months. If you are still encountering problems with this tool, please feel free to reopen the issue and provide any relevant error logs.

**Closed by icelam** 2023-01-01 08:36 UTC
